name: "デプロイとプレビューリンクのコメント"
description: "アプリケーションをデプロイし、GitHubのPRにプレビューリンクをコメントします"

inputs:
  vercel_url:
    description: "デプロイ先のURL"
    required: true
  app_name:
    description: "デプロイしたアプリケーションの名前"
    required: true
  pr_number:
    description: "PRの番号"
    required: true
  commit_sha:
    description: "コミットのSHA"
    required: true
  owner:
    description: "リポジトリのオーナー"
    required: true
  repo:
    description: "リポジトリの名前"
    required: true

runs:
  using: "composite"
  steps:
    - name: PRにプレビューリンクをコメント
      uses: actions/github-script@v6
      env:
        VERCEL_URL: ${{ inputs.vercel_url }}
        APP_NAME: ${{ inputs.app_name }}
      with:
        script: |
          const prNumber = "${{ inputs.pr_number }}";
          const commitSha = "${{ inputs.commit_sha }}";
          const appName = process.env.APP_NAME;
          const vercelUrl = process.env.VERCEL_URL;
          const owner = "${{ inputs.owner }}";
          const repo = "${{ inputs.repo }}";

          const commitUrl = `https://github.com/${owner}/${repo}/commit/${commitSha}`;

          const commentBody = `🚀 **${appName}のプレビュー環境が利用可能になりました**
          最新の変更がプレビュー環境にデプロイされました。

          🔗 **Vercel のデプロイ URL:** [${vercelUrl}](${vercelUrl})

          🔗 **コミット SHA:** [\`${commitSha}\`](${commitUrl})`;

          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: parseInt(prNumber),
            body: commentBody,
          });
