name: call

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_TEAM_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_WEB }}

on:
  workflow_call:
    inputs:
      diff:
        type: string
        description: "差分"
      ref:
        type: string
        description: "リファレンス"
    outputs:
      core_url:
        description: "core-apiのURL"
        value: ${{ jobs.call.outputs.core_url || '' }}

jobs:
  core_deploy:
    runs-on: ubuntu-latest
    if: ${{ inputs.diff == 'true' }}
    outputs:
      call_output: ${{ steps.call.outputs.test }}
      core_url: ${{ steps.call.outputs.core_url }}
    steps:
      - name: call
        id: call
        run: |
          echo "call"
          echo "ref: ${{ inputs.ref }}"
          echo "core_url=https://new-core-api.example.com" >> "$GITHUB_OUTPUT"

  deploy_skip:
    runs-on: ubuntu-latest
    if: ${{ inputs.diff == 'false' }}
    steps:
      - name: deploy_skip
        run: |
          echo "deploy skip"
