name: call

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_TEAM_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_WEB }}

on:
  workflow_call:
    inputs:
      ref:
        type: string
        description: "リファレンス"
      core_url:
        type: string
        description: "core-apiのURL"
      event_name:
        type: string
        description: "イベント名"
      pr_number:
        type: string
        description: "PRの番号"
      commit_sha:
        type: string
        description: "コミットのSHA"
      owner:
        type: string
        description: "リポジトリのオーナー"
      repo:
        type: string
        description: "リポジトリの名前"
    outputs:
      workflow_output:
        description: "ワークフローの出力"
        value: ${{ jobs.call.outputs.call_output }}
      url:
        description: "core-apiのURL"
        value: ${{ jobs.call.outputs.url }}

jobs:
  call:
    runs-on: ubuntu-latest
    env:
      APP_NAME: admin
    steps:
      - name: チェックアウト
        uses: actions/checkout@v3

      - name: ワークフローの出力を確認
        if: ${{ inputs.core_url != '' }}
        run: |
          echo "core_url: ${{ inputs.core_url }}"

      - name: ワークフローの出力を確認
        if: ${{ inputs.core_url == '' }}
        run: |
          echo "core_url: none"

      # - name: deploy
      #   uses: ./.github/actions/deploy
      #   with:
      #     ref: ${{ inputs.ref }}
      #     core_url: ${{ inputs.core_url }}

      - name: プルリクエストにプレビューリンクをコメント
        if: ${{ inputs.event_name == 'pull_request' }}
        uses: ./.github/actions/github/preview
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # vercel_url: ${{ env.DEPLOY_URL }}
          vercel_url: "https://admin-preview-20241212.vercel.app"
          app_name: ${{ env.APP_NAME }}
          pr_number: ${{ inputs.pr_number }}
          commit_sha: ${{ inputs.commit_sha }}
          owner: ${{ inputs.owner }}
          repo: ${{ inputs.repo }}
